library(tidyr)
library(dplyr)
library(ggrepel)
library(ggplot2)
library(stringr)
#optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/NP_and_basic_28.tsv", sep="\t") %>% group_by(language, basic) %>% summarise(Count=NROW(np)) %>% pivot_wider(names_from=basic, values_from=Count) %>% rename(Language=language)
optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/NP_and_basic.tsv", sep="\t")  %>% rename(Language=language) %>% group_by() %>% mutate(Language=str_replace(Language, "2.7", "2.8")) %>% mutate(Language=str_replace(Language, "2.6", "2.8")) %>% group_by(Language, basic) %>% summarise(Count=NROW(np)) %>% pivot_wider(names_from=basic, values_from=Count)
optim[is.na(optim$SVO),]$SVO=0
optim[is.na(optim$OSV),]$OSV=0
optim[is.na(optim$SOV),]$SOV=0
nrow(optim)
library(tidyr)  
library(dplyr)  
library(ggrepel)
library(ggplot2)
library(stringr)
#optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/NP_and_basic_28.tsv", sep="\t") %>% group_by(language, basic) %>% summarise(Count=NROW(np)) %>% pivot_wider(names_from=basic, values_from=Count) %>% rename(Language=language)   
optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/NP_and_basic.tsv", sep="\t")  %>% rename(Language=language) %>% group_by() %>% mutate(Language=str_replace(Language, "2.7", "2.8")) %>% mutate(Language=str_replace(Language, "2.6", "2.8")) %>% group_by(Language, basic) %>% summarise(Count=NROW(np)) %>% pivot_wider(names_from=basic, values_from=Count)
optim[is.na(optim$SVO),]$SVO=0  
optim[is.na(optim$OSV),]$OSV=0  
optim[is.na(optim$SOV),]$SOV=0  
u = read.csv("landscapes_noPOS_2.8_new.R.tsv", sep=" ")
u = merge(u, optim, by=c("Language"))   
u$AUCOptimizedCongruence = 1-u$SVO/(u$SVO+u$OSV+u$SOV)
#> cor.test(u$Congruence_All, u$AUCOptimizedCongruence)
uOldEnglish = data.frame(Language=c("Old_English"), Family=c("Germanic"), OSSameSideSum=c(10), OSSameSideTotal=c(13), OSSameSide=c(0.77), OFartherThanS=c(NA), OSSameSide_Real=c(NA), Congruence_VN=c(0.49))
u = rbind(u, uOldEnglish)
u = u %>% mutate(LogOSSameSide = log(OSSameSide+1e-10))
u = u %>% mutate(LogCongruence_VN = log(Congruence_VN+1e-10))
print(cor.test(u$Congruence_All, u$OSSameSide))
u$Language2 = as.character(u$Language)
for(i in (1:nrow(u))) {
        u$Language2[[i]] = str_replace(u$Language2[[i]], "_2.8", "")
        u$Language2[[i]] = str_replace(u$Language2[[i]], "_", " ")
} 
plot = ggplot(u, aes(x=Congruence_All, y=OSSameSide, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
plot
print(cor.test(u$Congruence_All, u$AUCOptimizedCongruence))
plot = ggplot(u, aes(x=Congruence_All, y=AUCOptimizedCongruence, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
plot
plot = ggplot(u, aes(x=Congruence_All, y=AUCOptimizedCongruence+OSSameSide, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
plot
print(cor.test(u$Congruence_All, u$AUCOptimizedCongruence+u$OSSameSide))
print(cor.test(u$Congruence_All, u$AUCOptimizedCongruence))
print(cor.test(u$Congruence_All, u$OSSameSide))
families = read.csv("genera_2.8.tsv", sep="\t")
u = merge(u, families, by=c("Language"), all.x=TRUE)
u$Family = u$Family.x
library(brms)
model = brm(OSSameSide ~ Congruence_All + (1+Congruence_All|Family) + (1+Congruence_All|Genus), data=u)
summary(model)
cor(u$OSSameSide, u$AUCOptimizedCongruence)
model = brm( Congruence_All~ AUCOptimizedCongruence + OSSameSide + (1+AUCOptimizedCongruence+OSSameSide|Family) + (1+AUCOptimizedCongruence+OSSameSide|Genus), data=u)
summary(model)
model = lmer( Congruence_All~ AUCOptimizedCongruence + OSSameSide + (1+AUCOptimizedCongruence+OSSameSide|Family) + (1+AUCOptimizedCongruence+OSSameSide|Genus), data=u)
library(lme4)
model = lmer( Congruence_All~ AUCOptimizedCongruence + OSSameSide + (1+AUCOptimizedCongruence+OSSameSide|Family) + (1+AUCOptimizedCongruence+OSSameSide|Genus), data=u)
model = lmer( Congruence_All~ AUCOptimizedCongruence + OSSameSide + (1+AUCOptimizedCongruence+OSSameSide|Family) + (1|Genus), data=u)
model = lmer( Congruence_All~ AUCOptimizedCongruence + OSSameSide + (1+AUCOptimizedCongruence+OSSameSide|Family) + (1|Genus), data=u)
model = lmer( Congruence_All~ AUCOptimizedCongruence + OSSameSide + (1|Family) + (1|Genus), data=u)
summary(model)
u$Together = u$AUCOptimizedCongruence + u$OSSameSide
model = lmer( Congruence_All~ Together + (1|Family) + (1|Genus), data=u)
summary(model)
plot = ggplot(u, aes(x=Congruence_All, y=AUCOptimizedCongruence+OSSameSide, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
plot
#optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/NP_and_basic_28.tsv", sep="\t") %>% group_by(language, basic) %>% summarise(Count=NROW(np)) %>% pivot_wider(names_from=basic, values_from=Count) %>% rename(Language=language)   
optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/NP_and_basic.tsv", sep="\t")  %>% rename(Language=language) %>% group_by() %>% mutate(Language=str_replace(Language, "2.7", "2.8")) %>% mutate(Language=str_replace(Language, "2.6", "2.8")) %>% mutate(Language=str_replace(Language, "-GSD", "")) %>% group_by(Language, basic) %>% summarise(Count=NROW(np)) %>% pivot_wider(names_from=basic, values_from=Count) 
optim[is.na(optim$SVO),]$SVO=0  
optim[is.na(optim$OSV),]$OSV=0  
optim[is.na(optim$SOV),]$SOV=0  
u = read.csv("landscapes_noPOS_2.8_new.R.tsv", sep=" ")
u = merge(u, optim, by=c("Language"))   
u$AUCOptimizedCongruence = 1-u$SVO/(u$SVO+u$OSV+u$SOV)
#> cor.test(u$Congruence_All, u$AUCOptimizedCongruence)
uOldEnglish = data.frame(Language=c("Old_English"), Family=c("Germanic"), OSSameSideSum=c(10), OSSameSideTotal=c(13), OSSameSide=c(0.77), OFartherThanS=c(NA), OSSameSide_Real=c(NA), Congruence_VN=c(0.49))
u = rbind(u, uOldEnglish)
u = u %>% mutate(LogOSSameSide = log(OSSameSide+1e-10))
u = u %>% mutate(LogCongruence_VN = log(Congruence_VN+1e-10))
sink("output/correlation.txt")
sink()
print(cor.test(u$Congruence_All, u$AUCOptimizedCongruence))
print(cor.test(u$Congruence_All, u$OSSameSide))
print(cor.test(u$Congruence_All, u$AUCOptimizedCongruence+u$OSSameSide))
u[ u$Language == "Japanese_2.8",]
u$Language2 = as.character(u$Language)
for(i in (1:nrow(u))) {
        u$Language2[[i]] = str_replace(u$Language2[[i]], "_2.8", "")
        u$Language2[[i]] = str_replace(u$Language2[[i]], "_", " ")
} 
plot = ggplot(u, aes(x=Congruence_All, y=OSSameSide, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
plot = ggplot(u, aes(x=Congruence_All, y=AUCOptimizedCongruence, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
plot = ggplot(u, aes(x=Congruence_All, y=AUCOptimizedCongruence+OSSameSide, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
plot
families = read.csv("genera_2.8.tsv", sep="\t")
u = merge(u, families, by=c("Language"), all.x=TRUE)
u$Family = u$Family.x
library(brms)
u$Together = u$AUCOptimizedCongruence + u$OSSameSide
model = brm( Congruence_All~ Together + (1+Together|Family) + (1+Together|Genus), data=u)
summary(model)
samples = posterior_samples(model)
mean(samples$b_Together<0)
model = brm( Congruence_All~ AUCOptimizedCongruence + (1+AUCOptimizedCongruence|Family) + (1+AUCOptimizedCongruence|Genus), data=u)
samples = posterior_samples(model)
mean(samples$b_AUCOptimizedCongruence<0)
model = brm( Congruence_All~ OSSameSide + (1+OSSameSide|Family) + (1+OSSameSide|Genus), data=u)
samples = posterior_samples(model)
mean(samples$b_OSSameSide<0)
plot = ggplot(u, aes(x=Congruence_All, y=OSSameSide, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
ggsave("figures/coadaptation-noPOS-dlm.pdf", height=7, width=7)
plot = ggplot(u, aes(x=Congruence_All, y=AUCOptimizedCongruence, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
ggsave("figures/coadaptation-noPOS-surprisal.pdf", height=7, width=7)
plot = ggplot(u, aes(x=Congruence_All, y=AUCOptimizedCongruence+OSSameSide, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
ggsave("figures/coadaptation-noPOS-joint.pdf", height=7, width=7)
print(cor.test(u$Congruence_All, u$AUCOptimizedCongruence))
print(cor.test(u$Congruence_All, u$OSSameSide))
print(cor.test(u$Congruence_All, u$AUCOptimizedCongruence+u$OSSameSide))
model1 = lmer( Congruence_All~ OSSameSide + (1+OSSameSide|Family) + (1+OSSameSide|Genus), data=u)
model2 = brm( Congruence_All~ Together + (1+Together|Family) + (1+Together|Genus), data=u)
model2 = lmer( Congruence_All~ Together + (1+Together|Family) + (1+Together|Genus), data=u)
model2 = lmer( Congruence_All~ Together + (1+Together|Family) + (1|Genus), data=u)
model1 = lmer( Congruence_All~ OSSameSide + (1+OSSameSide|Family) + (1|Genus), data=u)
anova(model2, model1)
anova(model1, model2)
plot = ggplot(u, aes(x=Congruence_All, y=(AUCOptimizedCongruence+OSSameSide)/2, color=Family)) + geom_text_repel(aes(label=Language2)) + xlab("Attested Subject-Object Position Congruence") + ylab("Optimized Subject-Object Position Congruence") + theme_bw() + theme(legend.position="none", axis.text=element_text(size=14), axis.title=element_text(size=16)) + theme(panel.grid = element_blank())
ggsave("figures/coadaptation-noPOS-joint.pdf", height=7, width=7)
print(cor.test(u$Congruence_All, u$AUCOptimizedCongruence+u$OSSameSide))
print(cor.test(u$Congruence_All, u$AUCOptimizedCongruence+u$OSSameSide, method="spearman"))
print(cor.test(u$Congruence_All, u$AUCOptimizedCongruence, method="spearman"))
print(cor.test(u$Congruence_All, u$OSSameSide, method="spearman"))
write.table(u, file="landscapes_NoPOS_2.8_VIZ_AUC.R.tsv")
library(tidyr)
library(dplyr)
library(ggrepel)
library(ggplot2)
library(stringr)
#optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/NP_and_basic_28.tsv", sep="\t") %>% group_by(language, basic) %>% summarise(Count=NROW(np)) %>% pivot_wider(names_from=basic, values_from=Count) %>% rename(Language=language)
optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/NP_and_basic.tsv", sep="\t")
library(tidyr)
library(dplyr)
library(ggrepel)
library(ggplot2)
library(stringr)
#optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/NP_and_basic_28.tsv", sep="\t") %>% group_by(language, basic) %>% summarise(Count=NROW(np)) %>% pivot_wider(names_from=basic, values_from=Count) %>% rename(Language=language)
optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/NP_and_basic.tsv", sep="\t")  %>% rename(Language=language) %>% group_by() %>% mutate(Language=str_replace(Language, "2.7", "2.8")) %>% mutate(Language=str_replace(Language, "2.6", "2.8")) %>% mutate(Language=str_replace(Language, "-GSD", ""))
optim
summary(optim$np)
mean(optim$Dist_A)
mean(optim$Dist_N)
mean(optim$Dist_D)
t.test(optim$Dist_D, optim$Dist_N)
t.test(optim$Dist_A, optim$Dist_N)
optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/grammars.tsv", sep="\t")  %>% rename(Language=language) %>% group_by() %>% mutate(Language=str_replace(Language, "2.7", "2.8")) %>% mutate(Language=str_replace(Language, "2.6", "2.8")) %>% mutate(Language=str_replace(Language, "-GSD", ""))
summary(optim)
optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/arguments.tsv", sep="\t")  %>% rename(Language=language) %>% group_by() %>% mutate(Language=str_replace(Language, "2.7", "2.8")) %>% mutate(Language=str_replace(Language, "2.6", "2.8")) %>% mutate(Language=str_replace(Language, "-GSD", ""))
summary(optim)
optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/grammars.tsv", sep="\t")  %>% rename(Language=language) %>% group_by() %>% mutate(Language=str_replace(Language, "2.7", "2.8")) %>% mutate(Language=str_replace(Language, "2.6", "2.8")) %>% mutate(Language=str_replace(Language, "-GSD", ""))
summary(optim)
optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/grammars.tsv", sep="\t")  %>% rename(Language=language) %>% group_by() %>% mutate(Language=str_replace(Language, "2.7", "2.8")) %>% mutate(Language=str_replace(Language, "2.6", "2.8")) %>% mutate(Language=str_replace(Language, "-GSD", "")) %>% group_by(Language, idForProcess)
summary(optim)
optim = read.csv("~/memsurp-optim/code/optimizeAUC/output/grammars.tsv", sep="\t")  %>% rename(Language=language) %>% group_by() %>% mutate(Language=str_replace(Language, "2.7", "2.8")) %>% mutate(Language=str_replace(Language, "2.6", "2.8")) %>% mutate(Language=str_replace(Language, "-GSD", "")) %>% group_by(Language, idForProcess) %>% pivot_wider(names_from=dependency, values_from=weight)
summary(optim)
optim %>% group_by(Language) %>% summarise(ACL = mean(acl < HEAD))
optim %>% group_by(Language) %>% summarise(ACL = mean((acl < HEAD)!=(obj<HEAD) ))
u = optim %>% group_by(Language) %>% summarise(ACL = mean((acl < HEAD)!=(obj<HEAD) ))
u[order(u$ACL),]
u[!order(u$ACL),]
u[order(-u$ACL),]
save_history()
savehistory()
